package com.santander.geta;

import com.santander.getafe.rules.WrapperEvent;
import static com.santander.getafe.factory.constants.GenericRecordConstants.*;
import org.apache.avro.generic.GenericRecord
import java.util.Date
import org.json.JSONObject
import java.io.StringWriter
import com.santander.getafe.factory.constants.GenericRecordConstants;
import java.util.ArrayList;
import java.util.List;
import java.util.Map
import org.json.JSONArray;
import java.util.stream.Collectors;


function String getSeverityLevel(String severity) {
    switch (severity) {
                case "AVAILABILITY":
                    return GenericRecordConstants.severityLevel.AVAILABILITY.toString();
                case "CUSTOM_ALERT":
                    return GenericRecordConstants.severityLevel.CUSTOM_ALERT.toString();
                case "ERROR":
                    return GenericRecordConstants.severityLevel.ERROR.toString();
                case "MONITORING_UNAVAILABLE":
                    return GenericRecordConstants.severityLevel.MONITORING_UNAVAILABLE.toString();
                 case "PERFORMANCE":
                    return GenericRecordConstants.severityLevel.PERFORMANCE.toString();
                case "RESOURCE_CONTENTION":
                    return GenericRecordConstants.severityLevel.RESOURCE_CONTENTION.toString();
            }
             return GenericRecordConstants.severityLevel.AVAILABILITY.toString();
}


